# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: addition.proto for package ''

require 'grpc'
require 'addition_pb'

module Addition
  class Service

    include ::GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Addition'

    rpc :Add, ::AddRequest, ::AddResponse
  end

  Stub = Service.rpc_stub_class
end
