# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addition.proto

require 'google/protobuf'


descriptor_data = "\n\x0e\x61\x64\x64ition.proto\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1a\n\x0b\x41\x64\x64Response\x12\x0b\n\x03sum\x18\x01 \x01(\x05\x32,\n\x08\x41\x64\x64ition\x12 \n\x03\x41\x64\x64\x12\x0b.AddRequest\x1a\x0c.AddResponseb\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

AddRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AddRequest").msgclass
AddResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("AddResponse").msgclass
