source "https://rubygems.org"

gem "json"

gem "sinatra"
# for live reload
gem "rerun"

gem "rackup"

gem "puma"

gem "grpc"

gem "grpc-tools"

gem "bunny"

gem "activerecord"

gem "pg"

gem "sinatra-activerecord"

gem "rake"
